### PR TITLE
Remove unnecessary code to make it work

### PR DESCRIPTION
**Pull request by pando85**
Hey, I had troubles with graphic `.so` libraries and it became in a segmentation crash when trying to run this so I removed that code that was not needed.

Running 6.1.69-1-MANJARO and Freecad 0.21.2

### CODE REVIEW

**Comment by clsergent** [comment]
Hi,

I deduced from your fork that you removed thumbnail generation. It allows to display a picture of the job on the snapmaker screen.
Did you try to add `--no-thumbnail` argument to fix your problem?

You also removed `getSelectedJob()`method, which is called in last resort to find attached PathJob.

Both require to have access to GUI, which seems to crash your program, as you stated.

I will neither remove thumbnail generation, nor `getSelectedJob()` methods, which are both usefull, but I could add another argument to prevent GUI calls (maybe `--no--gui`)*. 
Would you agree with my proposal?

*Actually, there is already a GUI check (`if FreeCAD.GuiUp:`) but I understand it fails in your case...

**Comment by pando85** [comment]
Hey @clsergent , 

yep. It sounds reasonable. I was in a hurry because I needed to cut some wood and I just did a dirty workaround. Adding that parameter and documenting it will help folks who have the same problem as me in the future.

I'm using the GUI but in an i3 desktop environment.
```bash
# uname -a
Linux XXXXXX 6.1.71-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jan  5 17:36:36 UTC 2024 x86_64 GNU/Linux
```
FreeCAD 0.21.2

After those changes, I could use your postscript, which worked like a charm.

Thank you very much.

**Comment by clsergent** [comment]
Hi,

Could you try running the postprocessor to check whether my last commit addresses your problem?
Thanks!

**Comment by pando85** [comment]
Hey,
Perfect, it works now. Could we do it in the other way around or document better the `--no-gui` parameter?
Thanks for your effort.

**Comment by clsergent** [comment]
Hi,

I understand your concern. I'm not willing to make `--no-gui` default: it removes both thumbnail generation (which make output files equivalent to what Luban can provide) and a fallback to find jobs to process. 
I agree with you on documenting this argument: I will insert a new item in the Wiki FAQ to help people struggling with graphic libraries.

**Pull request closed without merging**
